stepDegrees = 1.8
degreesInRotation = 360
stepsPerRotation = degreesInRotation/stepDegrees
xStepPin = 19
xDirPin = 26
yStepPin = 16
yDirPin = 20
servoControlPin = 21
centerX = 300
centerY = 500
cw = 1 #clockwise
ccw = 0 #counterclockwise
delay = 1 / stepsPerRotation